// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://liawkcjijuokmkerqmqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpYXdrY2ppanVva21rZXJxbXFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3OTg0MjMsImV4cCI6MjA4NzM3NDQyM30.dqmh8MvYLxGOnLlMec-AwtAMUtBV-BdQP1PpvCuiOqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});